[package]
name = "rust-caculator"
version = "1.0.0"
authors = ["VincentPT"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
lazy_static = "1.4.0"